name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
     # Log in to the GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker compose build

    - name: Tag Docker image
      run: |
         docker tag api_server:latest ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/api_server
         docker tag wds:latest ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/wds
      
    # Push the Docker image to GitHub Container Registry
    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/wds
        docker push ghcr.io/$(echo ${{ github.repository }} | awk '{print tolower($0)}')/api_server
