name: Migrate Data to mongo-db
on: workflow_dispatch

jobs:
  migrate:
    runs-on: ubuntu-latest
    container: mongo
    steps:
      - name: a
        run: ls -lAh $GITHUB_WORKSPACE
      - name: migrate
        run: mongoimport --db banking --collection accounts --file $GITHUB_WORKSPACE/data.json --jsonArray --uri "mongodb://162.55.191.34:27017/"
