name: Migrate Data to mongo-db
on: workflow_dispatch

jobs:
  migrate:
    runs-on: ubuntu-latest
    container: mongo
    steps:    
      - uses: actions/checkout@v4
       # Log in to the GitHub Container Registry
      - name: migrate
        run: mongoimport --db banking --collection accounts --file data.json --jsonArray --uri "mongodb://162.55.191.34:27017/"
