name: Deploy with SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 162.55.191.34 >> ~/.ssh/known_hosts

    - name: Copy index.js to server
      run: |
        scp -i ~/.ssh/id_rsa ./index.js root@162.55.191.34:/app/index.js
        scp -i ~/.ssh/id_rsa ./data.json root@162.55.191.34:/app/data.json
        ssh root@162.55.191.34 killall node
        ssh root@162.55.191.34 nohup node index.js


