name: Deploy with SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 162.55.191.34 >> ~/.ssh/known_hosts

    - name: Copy index.js to server
      run: |
        scp -i ~/.ssh/id_rsa ./*.js root@162.55.191.34:/app/
        scp -i ~/.ssh/id_rsa ./*.json root@162.55.191.34:/app/
        scp -i ~/.ssh/id_rsa ./*.html root@162.55.191.34:/app/
        scp -r -i ~/.ssh/id_rsa ./dev/ root@162.55.191.34:/app/
        ssh root@162.55.191.34 'ps -p $(cat /app/bank.pid)' || echo no server process running
        ssh root@162.55.191.34 'ps -p $(cat /app/api.pid)' || echo no node process running
        ssh root@162.55.191.34 'killall node' || echo no node process running
        ssh root@162.55.191.34 start-stop-daemon -K --remove-pidfile -m -p /app/bank.pid || echo no server process running
        ssh root@162.55.191.34 start-stop-daemon -K --remove-pidfile -m -p /app/api.pid || echo no node process running
        ssh root@162.55.191.34 'cd /app; npm install && npm update'
        ssh root@162.55.191.34 'start-stop-daemon -S -d /app -m -p /app/bank.pid -b -x $(which npm) -- run serve'
        ssh root@162.55.191.34 'start-stop-daemon -S -d /app -m -p /app/api.pid -b -x $(which node) -- index.js'
        ssh root@162.55.191.34 'ps -p $(cat /app/bank.pid)' || echo no server process running
        ssh root@162.55.191.34 'ps -p $(cat /app/api.pid)' || echo no node process running
